// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwyTsZnv5c6jmyDp9Sxp6rdg4k34s_S7c',
    appId: '1:392948734105:android:ee24e4921d6eae1ecd0008',
    messagingSenderId: '392948734105',
    projectId: 'm-mart-93570',
    storageBucket: 'm-mart-93570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQ1u4ZcXYVmhqbiXo9Ue2-p4wppW5LaA',
    appId: '1:392948734105:ios:c0934cc0ee2ec615cd0008',
    messagingSenderId: '392948734105',
    projectId: 'm-mart-93570',
    storageBucket: 'm-mart-93570.firebasestorage.app',
    androidClientId: '392948734105-c3go0vlkva51q52a2b4jt0bhslm0j0ff.apps.googleusercontent.com',
    iosClientId: '392948734105-asdjkmuc89f1e72ajmim8ivcph79ber9.apps.googleusercontent.com',
    iosBundleId: 'com.foriyana.foriyanaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR496dlqrfKFMMwgCtb9Zvm5lSbYqaN4A',
    appId: '1:392948734105:web:c01a79835b1b2ec1cd0008',
    messagingSenderId: '392948734105',
    projectId: 'm-mart-93570',
    authDomain: 'm-mart-93570.firebaseapp.com',
    storageBucket: 'm-mart-93570.firebasestorage.app',
    measurementId: 'G-TG3X913WQE',
  );
}
